---
- name: create {{ php_log_dir }}
  file: path={{ php_log_dir }} owner=apache group=apache mode=0755 state=directory

- name: create {{ php_log }}
  file: path={{ php_log }} owner=apache group=apache mode=0644 state=touch force=yes

- name: enable remi
  command: yum-config-manager --enable remi
- name: enable remi-php56
  command: yum-config-manager --enable remi-php56

- name: install php
  yum: pkg={{ item }} state=installed enablerepo=remi,remi-php56
  with_items:
    - php
    - php-devel
    - php-mysqlnd
    - php-mbstring
    - php-gd
    - php-cli
    - php-dbg
    - php-pecl-xdebug
    - php-pear
    - php-pecl-mailparse
    - php-opcache
  notify:
    - restart httpd

- name: copy 15-xdebug.ini
  copy: src=15-xdebug.ini dest=/etc/php.d/15-xdebug.ini backup=yes
- name: copy php_custom.ini
  copy: src=php_custom.ini dest=/etc/php.d/php_custom.ini backup=yes
  notify:
    - restart httpd
