---
- name: install mariadb-server
  yum: name=mariadb-server state=latest

- name: put my_custom.cnf
  copy: src=my_custom.cnf dest=/etc/my.cnf.d/my_custom.cnf backup=yes

- name: create {{ slow_log }}
  file: path={{ slow_log }} owner=mysql group=mysql mode=0640 state=touch force=yes

#- name: start mariadb
#  service: name=mariadb state=started enabled=yes
