---
- name: install packages
  yum: pkg={{ item }} state=installed
  with_items:
    - vim
    - git
    - tig
    - nkf
    - zsh
    - unzip
    - ack
    - telnet
    - lm_sensors
    - net-tools
    - screen
    - logwatch
    - mailx
