---
- name: install core packages
  yum: pkg={{ item }} state=installed
  with_items:
    - mailx
    - net-tools
    - screen
    - telnet
    - unzip
    - vim
    - wget
    - zip

- name: install base packages 
  yum: pkg={{ item }} state=installed
  with_items:
    - ack
    - w3m
    - git
    - tig
    - nkf
    - zsh
    - lm_sensors
    - logwatch
