---
- name: install mail
  yum: pkg={{ item }} state=installed
  with_items:
    - postfix
    - postfix-perl-scripts
    - dovecot
    - procmail
    - mutt
    - cyrus-sasl

- name: find Maildir
  stat: path=/etc/skel/Maildir
  register: result

- name: copy main.cf
  copy: >
    src=main.cf
    dest=/etc/postfix/main.cf
    backup=yes
  notify:
    - restart postfix
  when: not result.stat.exists
