---
- name: set timezone Japan
  file: src=/usr/share/zoneinfo/Japan dest=/etc/localtime state=link force=yes

- name: install crontab
  yum: pkg={{ item }} state=installed
  with_items:
    - crontabs
    - cronie

- name: start crond
  service: name=crond state=started enabled=yes
